// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS54cuNQTeCaaJz6h2DduEOTfT6nVAE14',
    appId: '1:104633790371:web:e7dbe6ac88cafea0dbf416',
    messagingSenderId: '104633790371',
    projectId: 'lecturas-app-805ec',
    authDomain: 'lecturas-app-805ec.firebaseapp.com',
    storageBucket: 'lecturas-app-805ec.firebasestorage.app',
    measurementId: 'G-T90V719KN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtl789lvbKqstFJb_-fubTM35VS4VZu6U',
    appId: '1:104633790371:android:9d4a31e57d581d0cdbf416',
    messagingSenderId: '104633790371',
    projectId: 'lecturas-app-805ec',
    storageBucket: 'lecturas-app-805ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtEhUhsJieHmv2T-rzDjNlDB3jB2APpRc',
    appId: '1:104633790371:ios:49bebde18937b74adbf416',
    messagingSenderId: '104633790371',
    projectId: 'lecturas-app-805ec',
    storageBucket: 'lecturas-app-805ec.firebasestorage.app',
    iosBundleId: 'com.example.rutasLecturaDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtEhUhsJieHmv2T-rzDjNlDB3jB2APpRc',
    appId: '1:104633790371:ios:49bebde18937b74adbf416',
    messagingSenderId: '104633790371',
    projectId: 'lecturas-app-805ec',
    storageBucket: 'lecturas-app-805ec.firebasestorage.app',
    iosBundleId: 'com.example.rutasLecturaDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS54cuNQTeCaaJz6h2DduEOTfT6nVAE14',
    appId: '1:104633790371:web:952eeeb456d8bf52dbf416',
    messagingSenderId: '104633790371',
    projectId: 'lecturas-app-805ec',
    authDomain: 'lecturas-app-805ec.firebaseapp.com',
    storageBucket: 'lecturas-app-805ec.firebasestorage.app',
    measurementId: 'G-GGPELCD8E4',
  );
}
